---
- name: Update AD groups information on Windows
  hosts: "{{ target }}" #Define the group of Windows servers in your inventory
  #become: true
  gather_facts: no
  roles:
    - ad_group_update_windows
