---
- name: Check if the old group exists      #check old group----
  win_command: net localgroup "{{ old_group_name }}"
  register: old_group_check
  ignore_errors: yes
  
- name: Set fact for old group existence
  set_fact:
    old_group_exists: "{{ old_group_check.rc == 0 }}"
  ### add in new code to check message
- name: Show message for old group existence 
  debug:
    msg: "Old group '{{ old_group_name }}' does not exist on the server."
  when: not old_group_exists
  
- name: Add new group 
  win_command: net localgroup "{{ new_group_name }}" /add
  when: action_type == "Add"
  register: new_group_add
  changed_when: new_group_add.rc == 0
  
  #need to add in gitlab code-------------------------------
- name: check status on new group addition
  debug:
    msg: "new group "{{ new_group_name }}"  added successfully"
  when: new_group_add.changed
  
- name: Check if the new group exists
  win_command: net localgroup "{{ new_group_name }}"
  register: new_group_check
  
- name: Set fact based on new group existence status
  set_fact:
    new_group_exists: "{{ new_group_check.rc == 0 }}"
    
- name: Delete old group
  win_command: net localgroup "{{ old_group_name }}" /delete
  when: action_type == "delete"
  register: old_group_delete
  changed_when: old_group_delete.rc == 0
  
- name: check status old group deletion
  debug:
    msg: "Old group "{{ old_group_name }}" deleted successfully"
  when: old_group_delete.changed

#Report
- name: Create report for target servers
  when: action_type == "report"
  set_fact:
    report_data: |
      Server Name: {{ inventory_hostname }}
      Old Group '{{ old_group_name }}' Exists: {{ old_group_exists }}
      {% if not old_group_exists %}
      Old Group '{{ old_group_name }}' does not exist.
      {% else %}
      Old Group '{{ old_group_name }}' was deleted.
      {% endif %}
      New Group '{{ new_group_name }}' Added: {{ new_group_added | default(false) }}
      New Group '{{ new_group_name }}' Exists: {{ new_group_exists }}
  
- name: Output the report to con
  when: action_type == "report"
  debug:
    msg: "Report "{{ report_data }}" created successfully"
    
- name: Save report to localhost file
  when: action_type == "report"
  copy:
    content: "{{ report_data }}"
    dest: "./reports/{{ inventory_hostname }}_report.txt"
  delegate_to: localhost
